name: Coveralls 

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  coveralls:

    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory:  'server'

    steps:
    - name: Cloning repo
      uses: actions/checkout@v2
    # BACKEND
    - name: Use Node.js ${{ matrix.node-version }} for BACKEND
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: './server/package-lock.json'
    - name: Install dependencies
      working-directory: ./server
      run: npm install
    - name: Generating coverage information
      run: npm run coverage
    - name: Sending info to coveralls
      run: npm run coveralls
    - name: Coveralls GitHub Action
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
