name: Coveralls 

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  coveralls:

    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory:  'server'

    steps:
    - name: Cloning repo
      uses: actions/checkout@v2
    # BACKEND
    - name: Use Node.js 16.x for BACKEND
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
        cache: 'npm'
        cache-dependency-path: './server/package-lock.json'
    - name: Install dependencies
      working-directory: ./server
      run: npm install
    - name: Generating coverage information
      run: npm run coveralls
    - name: Coveralls GitHub Action
      uses: coverallsapp/github-action@1.1.3
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: ${{ github.workspace }}/server/coverage/lcov.info

