# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Test

on:
  push: 
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    # FRONTEND
    - name: Use Node.js ${{ matrix.node-version }} for FRONTEND
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: './marvelapp/package-lock.json'
    - name: Install dependencies
      working-directory: ./marvelapp
      run: npm install
    - name: Tests
      working-directory: ./marvelapp
      run: npm test
    # BACKEND
    - name: Use Node.js ${{ matrix.node-version }} for BACKEND
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: './server/package-lock.json'
    - name: Install dependencies
      working-directory: ./server
      run: npm install
    - name: Tests
      working-directory: ./server
      run: npm test
